"""
Contest submission packer.

Generates solution.json files compatible with the flashinfer-bench-starter-kit
submission format from KernForge output directories.

Usage:
  # Pack a single kernel
  python -m kernforge.submit --kernel outputs/kernforge_hybrid_moe_25/moe_moe_fp8_.../global_best_kernel_25.py \
      --definition moe_fp8_block_scale_ds_routing_topk8_ng8_kg4_e32_h7168_i2048 \
      --name kernforge-moe-v1

  # Pack all best kernels from an output directory
  python -m kernforge.submit --output_dir outputs/kernforge_hybrid_mlsys26-contest_25_20260214/ \
      --name kernforge-v1
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Optional


def pack_single_kernel(
    kernel_code: str,
    definition: str,
    name: str = "kernforge-solution",
    author: str = "kernforge",
    language: str = "triton",
    entry_point: str = "main.py::run",
    destination_passing_style: bool = False,
) -> dict:
    """
    Pack a single kernel into solution.json format.

    Returns a dict that can be serialized to JSON and is compatible with
    flashinfer_bench Solution model.
    """
    return {
        "name": name,
        "definition": definition,
        "author": author,
        "description": f"Generated by KernForge AI kernel agent",
        "spec": {
            "language": language,
            "target_hardware": ["cuda"],
            "entry_point": entry_point,
            "dependencies": [],
            "destination_passing_style": destination_passing_style,
        },
        "sources": [
            {
                "path": "main.py",
                "content": kernel_code,
            }
        ],
    }


def pack_from_output_dir(
    output_dir: str,
    name_prefix: str = "kernforge",
    author: str = "kernforge",
    total_steps: Optional[int] = None,
) -> list[dict]:
    """
    Pack all best kernels from a KernForge output directory.

    Scans for global_best_kernel_*.py files and creates solution.json for each.
    Returns list of (definition_name, solution_dict) tuples.
    """
    results = []
    output_path = Path(output_dir)

    if not output_path.exists():
        raise FileNotFoundError(f"Output directory not found: {output_dir}")

    # Find all task subdirectories
    for task_dir in sorted(output_path.iterdir()):
        if not task_dir.is_dir():
            continue

        # Find the best kernel file
        kernel_files = sorted(task_dir.glob("global_best_kernel_*.py"), reverse=True)
        if not kernel_files:
            continue

        # Use the one matching total_steps, or the latest
        kernel_file = kernel_files[0]
        if total_steps:
            for kf in kernel_files:
                if f"kernel_{total_steps}.py" in kf.name:
                    kernel_file = kf
                    break

        # Read kernel code
        kernel_code = kernel_file.read_text()
        if not kernel_code.strip():
            continue

        # Extract definition name from directory name
        # Directory format: {level}_{problem_id}
        task_name = task_dir.name
        parts = task_name.split("_", 1)
        if len(parts) == 2:
            level, problem_id = parts
            definition = problem_id  # problem_id IS the definition name
        else:
            definition = task_name

        # Read metrics if available
        metrics_file = kernel_file.with_name(
            kernel_file.name.replace("kernel_", "metrics_").replace(".py", ".json")
        )
        metrics = None
        if metrics_file.exists():
            try:
                metrics = json.loads(metrics_file.read_text())
            except Exception:
                pass

        solution_name = f"{name_prefix}-{definition}"
        solution = pack_single_kernel(
            kernel_code=kernel_code,
            definition=definition,
            name=solution_name,
            author=author,
        )

        results.append(
            {
                "definition": definition,
                "solution": solution,
                "metrics": metrics,
                "source_file": str(kernel_file),
            }
        )

    return results


def write_solution_json(solution: dict, output_path: str):
    """Write solution dict to JSON file."""
    with open(output_path, "w") as f:
        json.dump(solution, f, indent=2)
    print(f"  Written: {output_path}")


def write_starter_kit(solution: dict, output_dir: str):
    """
    Write solution in starter-kit format:
      output_dir/
        config.toml
        solution/triton/main.py
    """
    os.makedirs(os.path.join(output_dir, "solution", "triton"), exist_ok=True)

    # Write kernel source using the same entry point layout as flashinfer-bench.
    kernel_code = solution["sources"][0]["content"]
    kernel_path = os.path.join(output_dir, "solution", "triton", "main.py")
    with open(kernel_path, "w") as f:
        f.write(kernel_code)

    # Write config.toml
    config = f"""[solution]
name = "{solution["name"]}"
definition = "{solution["definition"]}"
author = "{solution["author"]}"

[build]
language = "triton"
entry_point = "main.py::run"
"""
    config_path = os.path.join(output_dir, "config.toml")
    with open(config_path, "w") as f:
        f.write(config)

    # Write solution.json
    solution_json_path = os.path.join(output_dir, "solution.json")
    write_solution_json(solution, solution_json_path)

    print(f"  Starter kit: {output_dir}/")


def main():
    parser = argparse.ArgumentParser(
        description="Pack KernForge kernels for contest submission"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--kernel", type=str, help="Path to a single kernel .py file")
    group.add_argument(
        "--output_dir", type=str, help="Path to KernForge output directory"
    )

    parser.add_argument(
        "--definition", type=str, help="Definition name (required with --kernel)"
    )
    parser.add_argument(
        "--name", type=str, default="kernforge-solution", help="Solution name prefix"
    )
    parser.add_argument("--author", type=str, default="kernforge", help="Author name")
    parser.add_argument(
        "--total_steps",
        type=int,
        default=None,
        help="Match kernels with this step count",
    )
    parser.add_argument(
        "--format",
        choices=["json", "starter-kit", "both"],
        default="both",
        help="Output format",
    )
    parser.add_argument(
        "--out",
        type=str,
        default="submissions",
        help="Output directory for submissions",
    )

    args = parser.parse_args()

    os.makedirs(args.out, exist_ok=True)

    if args.kernel:
        if not args.definition:
            parser.error("--definition is required with --kernel")

        kernel_code = Path(args.kernel).read_text()
        solution = pack_single_kernel(
            kernel_code=kernel_code,
            definition=args.definition,
            name=args.name,
            author=args.author,
        )

        print(f"\nPacking single kernel for '{args.definition}':")
        if args.format in ("json", "both"):
            write_solution_json(solution, os.path.join(args.out, f"{args.name}.json"))
        if args.format in ("starter-kit", "both"):
            write_starter_kit(solution, os.path.join(args.out, args.name))

    else:
        print(f"\nScanning output directory: {args.output_dir}")
        results = pack_from_output_dir(
            args.output_dir,
            name_prefix=args.name,
            author=args.author,
            total_steps=args.total_steps,
        )

        if not results:
            print("No kernels found!")
            sys.exit(1)

        print(f"Found {len(results)} kernel(s):\n")
        for r in results:
            definition = r["definition"]
            metrics = r["metrics"]
            speedup = metrics.get("speedup", 0) if metrics else 0
            correct = metrics.get("correct", False) if metrics else False
            print(f"  {definition}: correct={correct}, speedup={speedup:.3f}")

            if args.format in ("json", "both"):
                write_solution_json(
                    r["solution"],
                    os.path.join(args.out, f"{args.name}-{definition}.json"),
                )
            if args.format in ("starter-kit", "both"):
                write_starter_kit(
                    r["solution"],
                    os.path.join(args.out, f"{args.name}-{definition}"),
                )

    print(f"\nAll submissions written to: {args.out}/")


if __name__ == "__main__":
    main()
